/**
 * POST /api/deploy-treasury
 * Body: { walletAddress: "0xUserWallet" }
 *
 * Deploys a TreasuryRebalancerDemo contract on Arc Testnet for the given wallet.
 * The backend deployer pays the gas — the user needs no Arc testnet ETH.
 *
 * Steps:
 *   1. Validate the wallet address
 *   2. Check registry — if already deployed, return existing address (idempotent)
 *   3. Deploy TreasuryRebalancerDemo(owner=userWallet, relayer=backendWallet)
 *   4. Save mapping to registry (Vercel KV or local JSON)
 *   5. Return contract address
 *
 * ⚠️  ARC_PRIVATE_KEY is the backend deployer wallet key. Never sent to the browser.
 *
 * Response:
 *   { success: true, contractAddress: "0x...", txHash: "0x...", alreadyExisted: bool }
 */

import { NextResponse }  from 'next/server';
import { ethers }        from 'ethers';
import { getTreasury, setTreasury } from '@/lib/registry';

// ── Contract artifact ─────────────────────────────────────────────────────────
// Generated by: npx hardhat compile  (in arc-contracts/)
// Then:         node scripts/export-demo-artifact.mjs
// This file MUST be committed to git for Vercel to have it at build time.
import artifact from '@/contracts/TreasuryRebalancerDemo.json';

export const maxDuration = 60; // seconds — needed for Vercel serverless

export async function POST(request) {
  let body;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }

  const { walletAddress } = body;

  // ── 1. Validate wallet address ─────────────────────────────────────────────
  if (!walletAddress || !/^0x[0-9a-fA-F]{40}$/.test(walletAddress)) {
    return NextResponse.json(
      { error: 'Invalid walletAddress. Must be a valid EVM address.' },
      { status: 400 }
    );
  }

  // ── 2. Check for existing contract (idempotent) ────────────────────────────
  const existing = await getTreasury(walletAddress);
  if (existing) {
    return NextResponse.json({
      success:       true,
      contractAddress: existing,
      alreadyExisted:  true,
    });
  }

  // ── 3. Validate server-side secrets ───────────────────────────────────────
  const arcPrivateKey = process.env.ARC_PRIVATE_KEY;
  const arcRpcUrl     = process.env.ARC_RPC_URL || 'https://rpc.testnet.arc.network';

  if (!arcPrivateKey) {
    return NextResponse.json(
      { error: 'Server config error: ARC_PRIVATE_KEY not set' },
      { status: 500 }
    );
  }

  // ── 4. Deploy TreasuryRebalancerDemo on Arc ────────────────────────────────
  try {
    const provider    = new ethers.JsonRpcProvider(arcRpcUrl);
    const deployer    = new ethers.Wallet(arcPrivateKey, provider);
    const factory     = new ethers.ContractFactory(
      artifact.abi,
      artifact.bytecode,
      deployer
    );

    console.log(`[deploy-treasury] Deploying for wallet: ${walletAddress}`);
    console.log(`[deploy-treasury] Deployer: ${deployer.address}`);

    // constructor(address _owner, address _relayer)
    const contract = await factory.deploy(
      walletAddress,   // owner = user's wallet
      deployer.address // relayer = our backend wallet
    );

    const deployTx      = contract.deploymentTransaction();
    const contractAddress = await contract.getAddress();
    await contract.waitForDeployment();

    console.log(`[deploy-treasury] Deployed at: ${contractAddress}`);
    console.log(`[deploy-treasury] Tx hash: ${deployTx?.hash}`);

    // ── 5. Save to registry ──────────────────────────────────────────────────
    await setTreasury(walletAddress, contractAddress);

    return NextResponse.json({
      success:         true,
      contractAddress,
      txHash:          deployTx?.hash,
      alreadyExisted:  false,
    });

  } catch (e) {
    console.error('[deploy-treasury] Deployment failed:', e);
    return NextResponse.json(
      { error: e.shortMessage ?? e.message ?? 'Deployment failed' },
      { status: 500 }
    );
  }
}
